-- Baseline schema for the orders domain.
--
-- In production the orders table is owned upstream and assumed to already exist
-- (see KIRODEMO-003 design.md). This demo application has no such table, so this
-- baseline migration provisions it to make the read-only order-history feature
-- runnable end to end. The order-history feature itself contributes only the
-- supporting index (see V2).
CREATE TABLE orders (
    id           BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL,
    order_date   TIMESTAMP     NOT NULL,
    status       VARCHAR(32)   NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL,
    currency     CHAR(3)       NOT NULL
);
